#ifndef __NL4_NETLINK_H__
#define __NL4_NETLINK_H__

#define NL4_GENL_NAME "nl4enc"
#define NL4_GENL_VERSION 1

enum nl4_cmd {
	NL4_CMD_UNSPEC,
	NL4_CMD_ADD_RULE,
	NL4_CMD_DELETE_RULE,
	NL4_CMD_LIST_RULES,
	NL4_CMD_FLUSH_RULES,
	__NL4_CMD_MAX,
};

#define NL4_CMD_MAX (__NL4_CMD_MAX - 1)

enum nl4_attr {
	NL4_ATTR_UNSPEC,
	NL4_ATTR_REMOTE_IPV4,
	NL4_ATTR_SERVICE_SIDE,
	NL4_ATTR_SERVICE_PORT,
	NL4_ATTR_SHARED_KEY,
	__NL4_ATTR_MAX,
};

#define NL4_ATTR_MAX (__NL4_ATTR_MAX - 1)

enum nl4_service_side {
	NL4_SERVICE_REMOTE = 1,
	NL4_SERVICE_LOCAL,
	NL4_SERVICE_ALL_PORTS,
	__NL4_SERVICE_SIDE_MAX,
};

#define NL4_SERVICE_SIDE_MAX (__NL4_SERVICE_SIDE_MAX - 1)
#define NL4_SHARED_KEY_LEN 32
#define NL4_SHARED_KEY_WORDS 8

#endif
